networks:
  snark.test:
    name: snark.test
    external: true

services:
  wit-dev:
    build: .
    container_name: snark
    ports:
      - "${WIT_PORT:-8100}:${INTERNAL_PORT:-8094}"
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: >
      sh -c "cd snark &&
             python manage.py migrate &&
             python manage.py seed_personas &&
             python manage.py runserver 0.0.0.0:$$INTERNAL_PORT"
    profiles:
      - dev
    networks:
      snark.test:
        aliases:
          - wit.snark.test

  wit-prod:
    build: .
    container_name: snark
    ports:
      - "${WIT_PORT:-8100}:${INTERNAL_PORT:-8094}"
    env_file:
      - ./.env
    command: >
      sh -c "cd snark &&
             python manage.py migrate &&
             python manage.py seed_personas &&
             gunicorn base.wsgi:application --bind 0.0.0.0:$$INTERNAL_PORT
             --workers 2 --threads 2 --max-requests 1000 --max-requests-jitter 100"
    profiles:
      - prod
    networks:
      snark.test:
        aliases:
          - wit.snark.test
