# Generated by Django 5.2.11 on 2026-02-21 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("system_prompt", models.TextField()),
                ("rules", models.JSONField(default=list)),
                ("tone", models.CharField(max_length=50)),
                ("temperature", models.FloatField(default=0.9)),
                ("max_tokens", models.IntegerField(default=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "personas",
            },
        ),
        migrations.CreateModel(
            name="ProviderConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_name", models.CharField(max_length=50, unique=True)),
                ("model_name", models.CharField(max_length=100)),
                ("api_key_env_var", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("settings", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "provider_configs",
            },
        ),
        migrations.CreateModel(
            name="ResponseLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_text", models.TextField(blank=True, default="")),
                ("response_text", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(default=0)),
                ("provider_name", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_logs",
                        to="wit.persona",
                    ),
                ),
            ],
            options={
                "db_table": "response_logs",
                "indexes": [
                    models.Index(
                        fields=["persona", "-created_at"],
                        name="response_lo_persona_c22813_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="response_lo_ip_addr_1d923d_idx",
                    ),
                ],
            },
        ),
    ]
