# Generated by Django 5.2.15 on 2026-06-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wit", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProviderConfig",
        ),
    ]
