# Generated by Django 5.2.15 on 2026-06-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wit", "0002_delete_providerconfig"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="responselog",
            name="response_lo_ip_addr_1d923d_idx",
        ),
        migrations.RemoveField(
            model_name="responselog",
            name="ip_address",
        ),
    ]
