# Generated by Django 5.2.15 on 2026-07-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wit", "0003_remove_responselog_response_lo_ip_addr_1d923d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="responselog",
            name="input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="responselog",
            name="output_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
