# Generated by Django 5.2.15 on 2026-07-01 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wit", "0004_responselog_input_tokens_responselog_output_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_name", models.CharField(max_length=50)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("success", models.BooleanField(default=True)),
                ("fell_back", models.BooleanField(default=False)),
                ("content_filtered", models.BooleanField(default=False)),
                ("streamed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="wit.persona",
                    ),
                ),
            ],
            options={
                "db_table": "generation_events",
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="generation__created_c6c5d2_idx"
                    )
                ],
            },
        ),
    ]
