# Generated by Django 5.2.15 on 2026-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wit", "0005_generationevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationevent",
            name="error_code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="generationevent",
            name="error_detail",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
